### ISSUE TITLE
Transcript overlay bug

### ISSUE THREAD

**Issue by limjoe** [ossrs/srs-stack#155]
**Describe the bug**
Transcript overlay occurs an error, cause srs-stack docker crash
 
**Version**
v5.12.21

**To Reproduce**
1. only modify mgmt/bootstrap config with data dir
2. run bash mgmt/bootstrap
3. start AI Transcription

**Expected behavior**
srs-stack should not to crash.

**Additional context**

srs-stack logs:

```
[2024-01-18 11:07:47.045][INFO][42][gi9rd5y6] http: on_hls ok, client_id=gi9rd5y6, url=http://localhost:2022/terraform/v1/hooks/srs/hls, request={"server_id":"vid-x32s68x","service_id":"26ns871d","action":"on_hls","client_id":"gi9r
d5y6","ip":"82.2.186.108","vhost":"__defaultVhost__","app":"live","tcUrl":"rtmp://194.164.17.17/live/QJWuW4ghWgnA?secret=5aac37d713414d8f88c11a414e8cc149","stream":"QJWuW4ghWgnA","param":"?secret=5aac37d713414d8f88c11a414e8cc149?se
cret=5aac37d713414d8f88c11a414e8cc149","duration":16.67,"cwd":"/usr/local/srs-stack/platform","file":"./objs/nginx/html/live/QJWuW4ghWgnA-130-1705576050377.ts","url":"live/QJWuW4ghWgnA-130-1705576050377.ts","m3u8":"./objs/nginx/htm
l/live/QJWuW4ghWgnA.m3u8","m3u8_url":"live/QJWuW4ghWgnA.m3u8","seq_no":130,"stream_url":"/live/QJWuW4ghWgnA","stream_id":"vid-1s195r1"}, response={"code":0,"data":null,"server":52}
[trace] 2024/01/18 11:07:47.094552 [52][1007] transcript persistence ok, cost=2.47463ms
[trace] 2024/01/18 11:07:47.461253 [52][1001] transcript generate m3u8 ok, uuid=bd4351c3-d556-4fce-975e-4140c8022aee, duration=16.67
[trace] 2024/01/18 11:07:47.640410 [52][1001] transcript server ts file ok, uuid=117-overlay-10878ad9-72b4-48fb-a04e-9cd90c41562b, ts=transcript/117-overlay-10878ad9-72b4-48fb-a04e-9cd90c41562b.ts
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:07:48.787][INFO][42][va84574y] Hybrid cpu=16.95%,31MB, cid=1,1, timer=60,0,0, clock=0,28,16,1,1,0,0,0,0, free=1, objs=(pkt:323,raw:50,fua:272,msg:554,oth:1,buf:50)
[trace] 2024/01/18 11:07:48.874698 [52][1006] transcript: extract audio transcript/130-org-98318c38-4f16-4cb9-a936-27f13d33ea08.ts to transcript/130-audio-ce76e810-dcf1-4999-a38c-3402a71f5aa1.m4a, size=65424, cost=1.721063006s
[trace] 2024/01/18 11:07:48.880510 [52][1007] transcript persistence ok, cost=4.456687ms
[trace] 2024/01/18 11:07:49.459960 [52][1001] Proxy /api/v1/streams/ to backend 1985
[2024-01-18 11:07:49.468][INFO][42][72i9q2mg] HTTP #0 127.0.0.1:46982 GET http://194.164.17.17:2022/api/v1/streams/, content-length=-1
[2024-01-18 11:07:49.470][INFO][42][72i9q2mg] TCP: before dispose resource(HttpConn)(0x7fec4408bfd0), conns=2, zombies=0, ign=0, inz=0, ind=0
[2024-01-18 11:07:49.470][WARN][42][72i9q2mg][104] client disconnect peer. ret=1007
[2024-01-18 11:07:49.470][INFO][42][wdb001ea] TCP: clear zombies=1 resources, conns=2, removing=0, unsubs=0
[2024-01-18 11:07:49.470][INFO][42][72i9q2mg] TCP: disposing #0 resource(HttpConn)(0x7fec4408bfd0), conns=2, disposing=1, zombies=0
[2024-01-18 11:07:50.829][INFO][42][oh690y8i] Process: cpu=16.00%,31MB, threads=2
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:07:52.606][INFO][42][gi9rd5y6] <- CPB time=1865401832, okbps=0,0,0, ikbps=10,2668,2668, mr=0/350, p1stpt=20000, pnt=5000
[2024-01-18 11:07:53.789][INFO][42][va84574y] Hybrid cpu=17.95%,31MB, cid=1,1, timer=60,0,0, clock=0,28,16,1,1,0,0,0,0, free=1, objs=(pkt:323,raw:50,fua:272,msg:554,oth:1,buf:50)
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:07:55.838][INFO][42][oh690y8i] Process: cpu=19.00%,31MB, threads=2
[2024-01-18 11:07:56.224][INFO][42][gi9rd5y6] -> HLS time=1874114372ms, sno=132, ts=QJWuW4ghWgnA-131-1705576067036.ts, dur=9200ms, dva=0p
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:07:58.790][INFO][42][va84574y] Hybrid cpu=17.03%,31MB, cid=1,1, timer=60,0,0, clock=0,29,14,2,1,0,0,0,0, free=1, objs=(pkt:334,raw:51,fua:283,msg:565,oth:1,buf:50)
[trace] 2024/01/18 11:07:59.459943 [52][1001] Proxy /api/v1/streams/ to backend 1985
[2024-01-18 11:07:59.464][INFO][42][78580807] HTTP #0 127.0.0.1:44932 GET http://194.164.17.17:2022/api/v1/streams/, content-length=-1
[2024-01-18 11:07:59.468][INFO][42][78580807] TCP: before dispose resource(HttpConn)(0x7fec441cf7f0), conns=2, zombies=0, ign=0, inz=0, ind=0
[2024-01-18 11:07:59.468][WARN][42][78580807][104] client disconnect peer. ret=1007
[2024-01-18 11:07:59.468][INFO][42][wdb001ea] TCP: clear zombies=1 resources, conns=2, removing=0, unsubs=0
[2024-01-18 11:07:59.468][INFO][42][78580807] TCP: disposing #0 resource(HttpConn)(0x7fec441cf7f0), conns=2, disposing=1, zombies=0
[trace] 2024/01/18 11:07:59.822185 [52][1006] transcript: overlay transcript/118-org-614331cb-8465-49e6-b32e-769dc2c4c763.ts to transcript/118-overlay-bb06b62f-340d-41c6-b216-55b31e28697e.ts, size=4663528, cost=17.614856814s
[trace] 2024/01/18 11:07:59.823485 [52][1007] transcript persistence ok, cost=1.214747ms
[trace] 2024/01/18 11:08:00.339431 [52][1007] transcript persistence ok, cost=3.498851ms
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:00.846][INFO][42][oh690y8i] Process: cpu=10.95%,31MB, threads=2
[2024-01-18 11:08:02.607][INFO][42][gi9rd5y6] <- CPB time=1875402327, okbps=0,0,0, ikbps=10,2668,2668, mr=0/350, p1stpt=20000, pnt=5000
[trace] 2024/01/18 11:08:02.727657 [52][1006] transcript: asr audio=transcript/128-audio-edf4d5d5-d864-41ba-bfcb-0e5b9131128e.m4a, prompt=Ричард Дэмерен был арестован вчера утром на 44-й улице Востока. Часы после того, как он был п
ризнан преступником, Дэмерен должен был держать письмо, извиняясь за его нападения на полицию. Дэмерен уже служил 90 дней, но теперь он мог бы получить еще больше., text=Ну, потому что хорошие новости тоже важны. Мы рады сообщить, 
что миссия была найдена. Вчера вечером мы сказали вам, что старший гражданин Мария Саппиер миссировала от дома. Она уходила с котом и потеряла его., cost=2.831877456s
[trace] 2024/01/18 11:08:02.732766 [52][1007] transcript persistence ok, cost=4.98572ms
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:03.791][INFO][42][va84574y] Hybrid cpu=17.98%,31MB, cid=1,1, timer=60,0,0, clock=0,29,14,2,1,0,0,0,0, free=1, objs=(pkt:334,raw:51,fua:283,msg:565,oth:1,buf:50)
[trace] 2024/01/18 11:08:03.792465 [52][1001] on_hls ok, {"server_id":"vid-x32s68x","service_id":"26ns871d","action":"on_hls","client_id":"gi9rd5y6","ip":"82.2.186.108","vhost":"__defaultVhost__","app":"live","tcUrl":"rtmp://194.16
4.17.17/live/QJWuW4ghWgnA?secret=5aac37d713414d8f88c11a414e8cc149","stream":"QJWuW4ghWgnA","param":"?secret=5aac37d713414d8f88c11a414e8cc149?secret=5aac37d713414d8f88c11a414e8cc149","duration":16.67,"cwd":"/usr/local/srs-stack/plat
form","file":"./objs/nginx/html/live/QJWuW4ghWgnA-131-1705576067036.ts","url":"live/QJWuW4ghWgnA-131-1705576067036.ts","m3u8":"./objs/nginx/html/live/QJWuW4ghWgnA.m3u8","m3u8_url":"live/QJWuW4ghWgnA.m3u8","seq_no":131,"stream_url":
"/live/QJWuW4ghWgnA","stream_id":"vid-1s195r1"}
[trace] 2024/01/18 11:08:03.793453 [52][1001] transcript action=on_hls, file=./objs/nginx/html/live/QJWuW4ghWgnA-131-1705576067036.ts, duration=16.67, seqno=131, m3u8_url=live/QJWuW4ghWgnA.m3u8, vhost=__defaultVhost__, app=live, st
ream=QJWuW4ghWgnA, url=live/QJWuW4ghWgnA-131-1705576067036.ts
[2024-01-18 11:08:03.793][INFO][42][gi9rd5y6] http: on_hls ok, client_id=gi9rd5y6, url=http://localhost:2022/terraform/v1/hooks/srs/hls, request={"server_id":"vid-x32s68x","service_id":"26ns871d","action":"on_hls","client_id":"gi9r
d5y6","ip":"82.2.186.108","vhost":"__defaultVhost__","app":"live","tcUrl":"rtmp://194.164.17.17/live/QJWuW4ghWgnA?secret=5aac37d713414d8f88c11a414e8cc149","stream":"QJWuW4ghWgnA","param":"?secret=5aac37d713414d8f88c11a414e8cc149?se
cret=5aac37d713414d8f88c11a414e8cc149","duration":16.67,"cwd":"/usr/local/srs-stack/platform","file":"./objs/nginx/html/live/QJWuW4ghWgnA-131-1705576067036.ts","url":"live/QJWuW4ghWgnA-131-1705576067036.ts","m3u8":"./objs/nginx/htm
l/live/QJWuW4ghWgnA.m3u8","m3u8_url":"live/QJWuW4ghWgnA.m3u8","seq_no":131,"stream_url":"/live/QJWuW4ghWgnA","stream_id":"vid-1s195r1"}, response={"code":0,"data":null,"server":52}
[trace] 2024/01/18 11:08:03.813372 [52][1007] transcript persistence ok, cost=979.877µs
[trace] 2024/01/18 11:08:04.453462 [52][1001] transcript generate m3u8 ok, uuid=bd4351c3-d556-4fce-975e-4140c8022aee, duration=16.67
[trace] 2024/01/18 11:08:04.609909 [52][1001] transcript server ts file ok, uuid=118-overlay-bb06b62f-340d-41c6-b216-55b31e28697e, ts=transcript/118-overlay-bb06b62f-340d-41c6-b216-55b31e28697e.ts
[trace] 2024/01/18 11:08:05.780250 [52][1006] transcript: extract audio transcript/131-org-5e6eff7b-23c4-4e5b-ab41-c6c3d6096646.ts to transcript/131-audio-dad2f09e-71d9-4f27-94ae-6599e6bd7b00.m4a, size=65550, cost=1.858421282s
[trace] 2024/01/18 11:08:05.786759 [52][1007] transcript persistence ok, cost=6.263387ms
[2024-01-18 11:08:05.853][INFO][42][oh690y8i] Process: cpu=18.02%,31MB, threads=2
[2024-01-18 11:08:06.261][INFO][42][gi9rd5y6] -> HLS time=1884133464ms, sno=133, ts=QJWuW4ghWgnA-132-1705576083788.ts, dur=2566ms, dva=0p
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:08.792][INFO][42][va84574y] Hybrid cpu=17.00%,31MB, cid=2,1, timer=60,0,0, clock=0,30,14,2,0,1,0,0,0, free=1, objs=(pkt:320,raw:51,fua:269,msg:551,oth:1,buf:50)
[trace] 2024/01/18 11:08:09.459298 [52][1001] Proxy /api/v1/streams/ to backend 1985
[2024-01-18 11:08:09.464][INFO][42][438354yq] HTTP #0 127.0.0.1:33520 GET http://194.164.17.17:2022/api/v1/streams/, content-length=-1
[2024-01-18 11:08:09.471][INFO][42][438354yq] TCP: before dispose resource(HttpConn)(0x7fec441beb50), conns=2, zombies=0, ign=0, inz=0, ind=0
[2024-01-18 11:08:09.472][WARN][42][438354yq][104] client disconnect peer. ret=1007
[2024-01-18 11:08:09.472][INFO][42][wdb001ea] TCP: clear zombies=1 resources, conns=2, removing=0, unsubs=0
[2024-01-18 11:08:09.472][INFO][42][438354yq] TCP: disposing #0 resource(HttpConn)(0x7fec441beb50), conns=2, disposing=1, zombies=0
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:10.863][INFO][42][oh690y8i] Process: cpu=16.00%,31MB, threads=2
[2024-01-18 11:08:12.608][INFO][42][gi9rd5y6] <- CPB time=1885414832, okbps=0,0,0, ikbps=10,2671,2668, mr=0/350, p1stpt=20000, pnt=5000
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.
0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:13.792][INFO][42][va84574y] Hybrid cpu=14.99%,31MB, cid=2,1, timer=60,0,0, clock=0,30,14,2,0,1,0,0,0, free=1, objs=(pkt:320,raw:51,fua:269,msg:551,oth:1,buf:50)
[trace] 2024/01/18 11:08:13.862248 [52][1002] Refresh ipv4=172.17.0.2, bestMatch=eth0, candidates=map[eth0:172.17.0.2]
[2024-01-18 11:08:15.870][INFO][42][oh690y8i] Process: cpu=17.96%,31MB, threads=2
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:16.258][INFO][42][gi9rd5y6] -> HLS time=1894141268ms, sno=133, ts=QJWuW4ghWgnA-132-1705576083788.ts, dur=12566ms, dva=0p
[trace] 2024/01/18 11:08:17.373517 [52][1006] transcript: overlay transcript/119-org-c1f5a8df-dfcc-42d9-a8b3-3565b6c6403f.ts to transcript/119-overlay-31c97a79-404a-4ac5-a013-c03ecbdd3e0d.ts, size=4213644, cost=16.949413393s
panic: reflect: slice index out of range [recovered]
        panic: reflect: slice index out of range

goroutine 84 [running]:
encoding/json.(*encodeState).marshal.func1()
        /usr/local/go/src/encoding/json/encode.go:328 +0x6e
panic({0x81cfc0, 0x977830})
        /usr/local/go/src/runtime/panic.go:838 +0x207
reflect.Value.Index({0x8146c0?, 0xc00030c320?, 0xc0002340c0?}, 0x0?)
        /usr/local/go/src/reflect/value.go:1366 +0x16d
encoding/json.arrayEncoder.encode({0x7f485bebbf18?}, 0xc0000a2200, {0x8146c0?, 0xc00030c320?, 0x7f4883b783c8?}, {0x17?, 0x40?})
        /usr/local/go/src/encoding/json/encode.go:916 +0x8e
encoding/json.sliceEncoder.encode({0xc0001195d0?}, 0xc0000a2200, {0x8146c0?, 0xc00030c320?, 0xc000186010?}, {0xb?, 0x0?})
        /usr/local/go/src/encoding/json/encode.go:889 +0x2ca
encoding/json.structEncoder.encode({{{0xc0000f23f0?, 0x0?, 0x0?}, 0xc0002fa540?}}, 0xc0000a2200, {0x8588a0?, 0xc00030c320?, 0x203000?}, {0x0, 0x1})
        /usr/local/go/src/encoding/json/encode.go:761 +0x1f4
encoding/json.ptrEncoder.encode({0xc0001197e8?}, 0xc0000a2200, {0x872e20?, 0xc000350040?, 0xc0000a2200?}, {0xa?, 0x0?})
        /usr/local/go/src/encoding/json/encode.go:945 +0x25e
encoding/json.structEncoder.encode({{{0xc0002fe000?, 0x404394?, 0x16000?}, 0xc0002fa5a0?}}, 0xc0000a2200, {0x89bb60?, 0xc000350000?, 0xc00002c138?}, {0x0, 0x1})

/usr/local/go/src/encoding/json/encode.go:761 +0x1f4
encoding/json.ptrEncoder.encode({0xc0000a2200?}, 0xc0000a2200, {0x8998c0?, 0xc000350000?, 0x8998c0?}, {0x48?, 0x2b?})
        /usr/local/go/src/encoding/json/encode.go:945 +0x25e
encoding/json.(*encodeState).reflectValue(0x0?, {0x8998c0?, 0xc000350000?, 0x40e847?}, {0x78?, 0x0?})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78
encoding/json.(*encodeState).marshal(0x6a87ae?, {0x8998c0?, 0xc000350000?}, {0x2b?, 0x0?})
        /usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.Marshal({0x8998c0, 0xc000350000})
        /usr/local/go/src/encoding/json/encode.go:161 +0x45
main.(*TranscriptTask).saveTask(0xc000350000, {0x97c0a8?, 0xc0001bcd00})
        /g/platform/transcript.go:1933 +0xf7
main.(*TranscriptTask).doTranscript(0xc000350000, {0x97c150, 0xc0002151a0})
        /g/platform/transcript.go:1365 +0x1ae
main.(*TranscriptTask).Run.func1({0x97c150, 0xc0002151a0})
        /g/platform/transcript.go:1327 +0x5f
main.(*TranscriptTask).Run(0xc000350000, {0x97c150, 0xc00031c570})
        /g/platform/transcript.go:1335 +0x1d3
main.(*TranscriptWorker).Start.func1()
        /g/platform/transcript.go:851 +0xca
created by main.(*TranscriptWorker).Start
        /g/platform/transcript.go:845 +0x605
Platform stopped, exit.  
BASH_SOURCE=auto/before_stop, REALPATH=/usr/local/srs-stack/platform/auto/before_stop, SCRIPT_DIR=/usr/local/srs-stack/platform/auto, WORK_DIR=/usr/local/srs-stack/platform
LoadEnv CLOUD=DOCKER REGION=ap-beijing, SOURCE=gitee
Try to notify the Redis server to save data
Redis server saved data: OK
Stop redis server
Stopping redis, pid=22   
[2024-01-18 11:08:18.793][INFO][42][va84574y] Hybrid cpu=14.00%,31MB, cid=2,1, timer=60,0,0, clock=0,30,14,2,0,1,0,0,0, free=1, objs=(pkt:320,raw:51,fua:269,msg:551,oth:1,buf:50)   
Stopped redis OK, pid=22 
[2024-01-18 11:08:18.793][INFO][42][va84574y] Hybrid cpu=14.00%,31MB, cid=2,1, timer=60,0,0, clock=0,30,14,2,0,1,0,0,0, free=1, objs=(pkt:320,raw:51,fua:269,msg:551,oth:1,buf:50)
Stopped redis OK, pid=22   
BASH_SOURCE=auto/stop_srs, REALPATH=/usr/local/srs-stack/platform/auto/stop_srs, SCRIPT_DIR=/usr/local/srs-stack/platform/auto, WORK_DIR=/usr/local/srs-stack/platform
Stop SRS server, WORK_DIR:/usr/local/srs-stack/platform
Stopping SRS, pid=42
[2024-01-18 11:08:18.824][INFO][42][d3oh8l8y] sig=15, user terminate program, fast quit
srs-stack 391cca43ac02 0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 5060/tcp, 8080/tcp, 0.0.0.0:8000->8000/udp, :::8000->8000/udp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 9000/tcp, 0.0.0.0:10080->10080/udp, :::10080->10080/udp
[2024-01-18 11:08:19.489][INFO][42][d3oh8l8y] cleanup for quit signal fast=1, grace=0
[2024-01-18 11:08:19.876][INFO][42][oh690y8i] quit for thread #2(hybrid) finished
Stopped SRS OK, pid=42
Platform container not found
srs-stack
srs-stack
```

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs-stack/commit/366cdbcd9c9a0dd00a011540a3bfd8b116287553
